wave1 = startEnemySettings()
group = glueAddEnemyGroup(wave1)

glueSetEnemyCount(group,1)
glueSetLuaScript(group,"luaScript/Stage3/Group1.lua")
glueSetImage(group,NormalEnemy)
glueSetInitPos(group, 150.0,80.0)
glueSetSpeed(group,0.1,0.1)
glueSetHP(group,1)
glueSetTexScale(group,0.1)
glueAddBulletDir(group,0.2,0.8)
glueSetBulletSpeed(group,0.1)
glueSetBulletTexture(group,RedBullet,1.0)
glueSetBulletRate(group,0.5)

wave2 = startEnemySettings()
group2 = glueAddEnemyGroup(wave2)

glueSetEnemyCount(group2,1)
glueSetDelayFrame(group2,1000)
glueSetLuaScript(group2,"luaScript/Stage3/Group1.lua")
glueSetImage(group2,NormalEnemy)
glueSetInitPos(group2, 100.0,100.0)
glueSetSpeed(group2,0.05,0.05)
glueSetHP(group2,1)
glueSetTexScale(group2,0.1)
glueAddBulletDir(group2,0.2,0.8)
glueAddBulletDir(group2,-0.2,0.8)
glueSetBulletSpeed(group2,0.1)
glueSetBulletTexture(group2,RedBullet,1.0)
glueSetBulletRate(group2,0.5)

wave3 = startEnemySettings()
group3 = glueAddEnemyGroup(wave3)

glueSetEnemyCount(group3,2)
glueSetDelayFrame(group3,1000)
glueSetLuaScript(group3,"luaScript/Stage3/Group2.lua")
glueSetImage(group3,NormalEnemy)
glueSetInitPos(group3, SCREEN_WIDTH / 2,(SCREEN_HEIGHT / 2) - 200)
glueSetSpeed(group3,0.1,0.1)
glueSetHP(group3,1)
glueSetTexScale(group3,0.1)
glueAddBulletDir(group3,0.2,0.8)
glueAddBulletDir(group3,-0.2,0.8)
glueSetBulletSpeed(group3,0.1)
glueSetBulletTexture(group3,RedBullet,1.0)
glueSetBulletRate(group3,0.5)

wave4 = startEnemySettings()
group4 = glueAddEnemyGroup(wave4)

glueSetEnemyCount(group4,2)
glueSetDelayFrame(group4,1000)
glueSetLuaScript(group4,"luaScript/Stage3/Group1.lua")
glueSetImage(group4,NormalEnemy)
glueSetInitPos(group4, SCREEN_WIDTH / 2,(SCREEN_HEIGHT / 2) - 200)
glueSetSpeed(group4,0.1,0.1)
glueSetHP(group4,1)
glueSetTexScale(group4,0.1)
glueAddBulletDir(group4,0.0,1.0)
glueAddBulletDir(group4,0.5,0.5)
glueAddBulletDir(group4,-0.5,0.5)
glueSetBulletSpeed(group4,0.1)
glueSetBulletTexture(group4,RedBullet,1.0)
glueSetBulletRate(group4,0.5)

glueSetImage(Player,BossEnemy)
glueSetTexScale(Player,0.1)
glueSetBulletTexture(Player,BlueBullet,1.0)
glueAddBulletDir(Player,0.0,-1.0)
glueSetBulletSpeed(Player,0.7)
glueSetBulletRate(Player,0.2)
glueSetHP(Player,3)